// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModDownloads.Server.Context;

namespace ModDownloads.Server.Migrations
{
    [DbContext(typeof(DownloadsContext))]
    partial class DownloadsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("ModDownloads.Shared.Entities.Download", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Downloads");

                    b.Property<int>("ModId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("ID");

                    b.HasIndex("ModId");

                    b.ToTable("Download");
                });

            modelBuilder.Entity("ModDownloads.Shared.Entities.Mod", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("URL")
                        .IsRequired();

                    b.HasKey("ID");

                    b.ToTable("Mod");
                });

            modelBuilder.Entity("ModDownloads.Shared.Entities.Download", b =>
                {
                    b.HasOne("ModDownloads.Shared.Entities.Mod", "Mod")
                        .WithMany("Downloads")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
