dist: xenial
language: csharp
solution: ModDownloads.sln
mono: none
dotnet: 2.2.105

script:
 - dotnet restore
 - dotnet tool install --global dotnet-sonarscanner
 - dotnet sonarscanner begin /k:"dennisblokland_ModDownloads" /d:sonar.organization="dennisblokland-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_KEY" || true
 - dotnet build
 - dotnet sonarscanner end /d:sonar.login="$SONAR_KEY" || true