dist: xenial
language: csharp
solution: ModDownloads.sln
mono: none
dotnet: 2.2.105
install:
 - dotnet restore
 - dotnet tool install --global dotnet-sonarscanner
 
before_script:
  - export PATH="$PATH:$HOME/.dotnet/tools"
  
script:

 - dotnet sonarscanner begin /k:"dennisblokland_ModDownloads"  /o:"dennisblokland-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$SONAR_KEY"
 - dotnet build
 - dotnet sonarscanner end /d:sonar.login="$SONAR_KEY"