// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModDownloads.Server.Context;

namespace ModDownloads.Server.Migrations
{
    [DbContext(typeof(DownloadsContext))]
    [Migration("20190214124856_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ModDownloads.Shared.Entities.Download", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Downloads");

                    b.Property<int>("ModId");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("Download");
                });

            modelBuilder.Entity("ModDownloads.Shared.Entities.Mod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("URL")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Mod");
                });

            modelBuilder.Entity("ModDownloads.Shared.Entities.Download", b =>
                {
                    b.HasOne("ModDownloads.Shared.Entities.Mod", "Mod")
                        .WithMany("Downloads")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
